In [1]:
print("hello world")

hello world


In [4]:
import numpy as np

In [6]:
# Creating 5x4 array
array = np.arange(20).reshape(5, 4)
print(array)
print()

print(np.argmax(array))

print(np.argmax(array, axis=1))

print(np.argmax(array, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

19
[3 3 3 3 3]
[4 4 4 4]


In [7]:

array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])

newRow = np.array([2, 1, 8])
newArray = np.vstack((array, newRow))
print(newArray)

[[ 3  2  8]
 [ 4 12 34]
 [23 12 67]
 [ 2  1  8]]


In [8]:
array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])

newColumn = np.array([2, 1, 8])
newArray = np.column_stack((array, newColumn))
print(newArray)

[[ 3  2  8  2]
 [ 4 12 34  1]
 [23 12 67  8]]


In [9]:
matrix1 = [
    [3, 4, 2],
    [5, 1, 8],
    [3, 1, 9]
]

matrix2 = [
    [3, 7, 5],
    [2, 9, 8],
    [1, 5, 8]
]

result = np.dot(matrix1, matrix2)
print(result)

[[19 67 63]
 [25 84 97]
 [20 75 95]]


In [10]:
n = 8

# Create a nxn matrix filled with 0
matrix = np.zeros((n, n), dtype=int)

# fill 1 with alternate rows and column
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

# Print the checkerboard pattern
for i in range(n):
    for j in range(n):
        print(matrix[i][j], end=" ")
    print()

0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


In [11]:
x = np.array([1, 2])  
print(x.dtype)         
 
x = np.array([1.0, 2.0]) 
print(x.dtype)  
 
x = np.array([1, 2], dtype = np.int64)   
print(x.dtype)

int32
float64
int64


In [12]:
arr1 = np.array([[4, 7], [2, 6]], dtype=np.float64)
arr2 = np.array([[3, 6], [2, 8]], dtype=np.float64)

print(np.add(arr1, arr2))
print(np.sum(arr1))
print(np.sqrt(arr1))
print(arr1.T)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [ ]:
import